insert into book (book_id, title, publication_year, pages, publisher_id) values (1, 'Atomic Cafe, The', 1998, '950', 1);
insert into book (book_id, title, publication_year, pages, publisher_id) values (2, 'Hôtel des Invalides', 2004, null, 2);
insert into book (book_id, title, publication_year, pages, publisher_id) values (3, 'Dark Prince: The True Story of Dracula', 1997, '35', 3);
insert into book (book_id, title, publication_year, pages, publisher_id) values (4, 'Sparrow (a.k.a. Cultured Bird) (Man jeuk)', 2008, '20', 4);
insert into book (book_id, title, publication_year, pages, publisher_id) values (5, 'Angel-A', 2000, '126', 5);
insert into book (book_id, title, publication_year, pages, publisher_id) values (6, 'My Little Eye', 2002, '75439', 6);
insert into book (book_id, title, publication_year, pages, publisher_id) values (7, 'Story of Xinghua, The (Xinghua san yue tian)', null, null, 7);
insert into book (book_id, title, publication_year, pages, publisher_id) values (8, 'Comic-Con Episode IV: A Fan''s Hope', 1992, null, 8);
insert into book (book_id, title, publication_year, pages, publisher_id) values (9, 'Blood, Sweat + Vinyl: DIY in the 21st Century', 2005, '6', 9);
insert into book (book_id, title, publication_year, pages, publisher_id) values (10, 'Watcher, The', 1985, '53', 10);
insert into book (book_id, title, publication_year, pages, publisher_id) values (11, 'Cyclomania', 2009, '2915', 11);
insert into book (book_id, title, publication_year, pages, publisher_id) values (12, 'Carnosaur 3: Primal Species', 1992, '3253', 12);
insert into book (book_id, title, publication_year, pages, publisher_id) values (13, 'Intolerance: Love''s Struggle Throughout the Ages', 1997, '62293', 13);
insert into book (book_id, title, publication_year, pages, publisher_id) values (14, 'Vicky Cristina Barcelona', 2001, '60313', 14);
insert into book (book_id, title, publication_year, pages, publisher_id) values (15, 'Love God?, The', 1999, '3', 15);
insert into book (book_id, title, publication_year, pages, publisher_id) values (16, 'Soft Shell Man (Un crabe dans la tête)', 2004, '0038', 16);
insert into book (book_id, title, publication_year, pages, publisher_id) values (17, 'Torpedo Bombers (Torpedonostsy)', null, '21174', 17);
insert into book (book_id, title, publication_year, pages, publisher_id) values (18, 'Blind Pig Who Wants to Fly (Babi buta yang ingin terbang)', null, null, 18);
insert into book (book_id, title, publication_year, pages, publisher_id) values (19, 'I, Madman', null, '37210', 19);
insert into book (book_id, title, publication_year, pages, publisher_id) values (20, 'Canterbury Tale, A', null, '82', 20);
insert into book (book_id, title, publication_year, pages, publisher_id) values (21, 'Stoker', 2009, '507', 21);
insert into book (book_id, title, publication_year, pages, publisher_id) values (22, 'Closing the Ring', 2007, '90', 22);
insert into book (book_id, title, publication_year, pages, publisher_id) values (23, 'Thunderbird Six', null, null, 23);
insert into book (book_id, title, publication_year, pages, publisher_id) values (24, 'Showdown in Little Tokyo', 2010, '33', 24);
insert into book (book_id, title, publication_year, pages, publisher_id) values (25, 'Operation Daybreak', 1994, '2', 25);
insert into book (book_id, title, publication_year, pages, publisher_id) values (26, 'Farewell to Matyora', null, null, 26);
insert into book (book_id, title, publication_year, pages, publisher_id) values (27, 'Turtles Can Fly (Lakposhtha hâm parvaz mikonand)', 1988, '67207', 27);
insert into book (book_id, title, publication_year, pages, publisher_id) values (28, 'Birdwatchers (BirdWatchers - La terra degli uomini rossi)', 1996, '734', 28);
insert into book (book_id, title, publication_year, pages, publisher_id) values (29, 'Madadayo (a.k.a. Not Yet)', 1992, '166', 29);
insert into book (book_id, title, publication_year, pages, publisher_id) values (30, 'Shanghai', 2011, '37153', 30);
insert into book (book_id, title, publication_year, pages, publisher_id) values (31, 'Take a Giant Step', 1985, '8827', 31);
insert into book (book_id, title, publication_year, pages, publisher_id) values (32, 'Human Lanterns (Ren pi deng long)', null, '185', 32);
insert into book (book_id, title, publication_year, pages, publisher_id) values (33, 'Joni''s Promise', 2006, '0548', 33);
insert into book (book_id, title, publication_year, pages, publisher_id) values (34, 'FearDotCom (a.k.a. Fear.com) (a.k.a. Fear Dot Com)', 1993, '9', 34);
insert into book (book_id, title, publication_year, pages, publisher_id) values (35, 'Love in Another Language (Baska Dilde Ask)', 1992, '5278', 35);
insert into book (book_id, title, publication_year, pages, publisher_id) values (36, 'Miracle', 1988, '6059', 36);
insert into book (book_id, title, publication_year, pages, publisher_id) values (37, 'Nanayo (Nanayomachi)', 2008, '7551', 37);
insert into book (book_id, title, publication_year, pages, publisher_id) values (38, 'You Are So Beautiful (Je vous trouve très beau)', 2003, '288', 38);
insert into book (book_id, title, publication_year, pages, publisher_id) values (39, 'Anything Else', 2001, '3', 39);
insert into book (book_id, title, publication_year, pages, publisher_id) values (40, 'Dating the Enemy', 2002, '99731', 40);
insert into book (book_id, title, publication_year, pages, publisher_id) values (41, 'Up the Down Staircase', 2008, '04134', 41);
insert into book (book_id, title, publication_year, pages, publisher_id) values (42, 'Agatha', 2010, '41748', 42);
insert into book (book_id, title, publication_year, pages, publisher_id) values (43, 'Doubting Thomas', 2007, '20', 43);
insert into book (book_id, title, publication_year, pages, publisher_id) values (44, 'Die Another Day', 1997, '4129', 44);
insert into book (book_id, title, publication_year, pages, publisher_id) values (45, 'Crow, The: Wicked Prayer', 2009, '4905', 45);
insert into book (book_id, title, publication_year, pages, publisher_id) values (46, 'Surfer, Dude', 1999, '05', 46);
insert into book (book_id, title, publication_year, pages, publisher_id) values (47, 'Gold', 2006, null, 47);
insert into book (book_id, title, publication_year, pages, publisher_id) values (48, 'Return of Martin Guerre, The (Retour de Martin Guerre, Le)', 1996, '9', 48);
insert into book (book_id, title, publication_year, pages, publisher_id) values (49, 'Napoléon', 2004, '4974', 49);
insert into book (book_id, title, publication_year, pages, publisher_id) values (50, 'Down to the Sea in Ships', 2007, '633', 50);