insert into review (book_id, user_id, comment, date_posted) values (1, 1, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2020-08-07');
insert into review (book_id, user_id, comment, date_posted) values (2, 2, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '2024-02-29');
insert into review (book_id, user_id, comment, date_posted) values (3, 3, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2020-08-07');
insert into review (book_id, user_id, comment, date_posted) values (4, 4, 'Vivamus tortor.', '2019-11-24');
insert into review (book_id, user_id, comment, date_posted) values (5, 5, null, '2021-09-19');
insert into review (book_id, user_id, comment, date_posted) values (6, 6, 'Fusce posuere felis sed lacus.', '2020-12-10');
insert into review (book_id, user_id, comment, date_posted) values (7, 7, null, '2023-04-22');
insert into review (book_id, user_id, comment, date_posted) values (8, 8, null, '2021-08-30');
insert into review (book_id, user_id, comment, date_posted) values (9, 9, 'Proin interdum mauris non ligula pellentesque ultrices.', '2024-04-08');
insert into review (book_id, user_id, comment, date_posted) values (10, 10, null, '2022-06-25');
insert into review (book_id, user_id, comment, date_posted) values (11, 11, null, '2022-11-02');
insert into review (book_id, user_id, comment, date_posted) values (12, 12, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2023-11-19');
insert into review (book_id, user_id, comment, date_posted) values (13, 13, 'Morbi non quam nec dui luctus rutrum.', '2020-08-07');
insert into review (book_id, user_id, comment, date_posted) values (14, 14, null, '2021-11-13');
insert into review (book_id, user_id, comment, date_posted) values (15, 15, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '2021-02-18');
insert into review (book_id, user_id, comment, date_posted) values (16, 16, 'Nam nulla.', '2022-07-16');
insert into review (book_id, user_id, comment, date_posted) values (17, 17, 'Vivamus in felis eu sapien cursus vestibulum.', '2023-08-14');
insert into review (book_id, user_id, comment, date_posted) values (18, 18, 'Aliquam quis turpis eget elit sodales scelerisque.', '2021-09-20');
insert into review (book_id, user_id, comment, date_posted) values (19, 19, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '2021-03-03');
insert into review (book_id, user_id, comment, date_posted) values (20, 20, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2023-04-16');
insert into review (book_id, user_id, comment, date_posted) values (21, 21, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2020-02-04');
insert into review (book_id, user_id, comment, date_posted) values (22, 22, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2020-08-07');
insert into review (book_id, user_id, comment, date_posted) values (23, 23, 'Morbi porttitor lorem id ligula.', '2020-11-04');
insert into review (book_id, user_id, comment, date_posted) values (24, 24, 'Maecenas tincidunt lacus at velit.', '2022-05-22');
insert into review (book_id, user_id, comment, date_posted) values (25, 25, null, '2020-09-05');
insert into review (book_id, user_id, comment, date_posted) values (26, 26, 'Duis bibendum.', '2020-06-16');
insert into review (book_id, user_id, comment, date_posted) values (27, 27, null, '2022-01-17');
insert into review (book_id, user_id, comment, date_posted) values (28, 28, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2020-12-14');
insert into review (book_id, user_id, comment, date_posted) values (29, 29, null, '2023-11-16');
insert into review (book_id, user_id, comment, date_posted) values (30, 30, 'In hac habitasse platea dictumst.', '2020-08-07');
insert into review (book_id, user_id, comment, date_posted) values (31, 31, 'Cras in purus eu magna vulputate luctus.', '2023-06-30');
insert into review (book_id, user_id, comment, date_posted) values (32, 32, null, '2021-10-17');
insert into review (book_id, user_id, comment, date_posted) values (33, 33, 'Integer tincidunt ante vel ipsum.', '2023-09-29');
insert into review (book_id, user_id, comment, date_posted) values (34, 34, 'Morbi non quam nec dui luctus rutrum.', '2022-03-29');
insert into review (book_id, user_id, comment, date_posted) values (35, 35, 'Vivamus tortor.', '2024-03-12');
insert into review (book_id, user_id, comment, date_posted) values (36, 36, 'Nulla nisl.', '2022-10-21');
insert into review (book_id, user_id, comment, date_posted) values (37, 37, null, '2020-11-20');
insert into review (book_id, user_id, comment, date_posted) values (38, 38, 'Aliquam quis turpis eget elit sodales scelerisque.', '2022-02-23');
insert into review (book_id, user_id, comment, date_posted) values (39, 39, null, '2023-11-15');
insert into review (book_id, user_id, comment, date_posted) values (40, 40, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2023-04-24');
insert into review (book_id, user_id, comment, date_posted) values (41, 41, null, '2020-10-19');
insert into review (book_id, user_id, comment, date_posted) values (42, 42, 'Vivamus in felis eu sapien cursus vestibulum.', '2022-11-14');
insert into review (book_id, user_id, comment, date_posted) values (43, 43, 'Praesent id massa id nisl venenatis lacinia.', '2023-07-29');
insert into review (book_id, user_id, comment, date_posted) values (44, 44, 'Donec ut mauris eget massa tempor convallis.', '2020-08-29');
insert into review (book_id, user_id, comment, date_posted) values (45, 45, null, '2023-01-15');
insert into review (book_id, user_id, comment, date_posted) values (46, 46, 'Donec quis orci eget orci vehicula condimentum.', '2020-08-07');
insert into review (book_id, user_id, comment, date_posted) values (47, 47, null, '2022-07-05');
insert into review (book_id, user_id, comment, date_posted) values (48, 48, null, '2021-04-06');
insert into review (book_id, user_id, comment, date_posted) values (49, 49, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '2024-04-22');
insert into review (book_id, user_id, comment, date_posted) values (50, 50, 'Proin eu mi.', '2020-06-18');